name: Cancel
on:
  workflow_run:
    workflows: ['automerge', 'build', 'codeql-analysis']
    types:
      - requested
permissions:
  actions: write
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@de53429d2f5cdb27e4ebc02da1261d62da650d24
        name: Cancel Previous Workflow Runs
        with:
          workflow_id: ${{ github.event.workflow.id }}
